$(document).ready(function () {


    for (let i = 0; i < catalog.length; i++) {
        var bigCol = $("<div class='col-4'>")
        $(".dermo").append(bigCol)
        var bigRow = $("<div class='row'>")
        bigCol.append(bigRow)
        var colImg = $("<div class='col-3'>")
        bigRow.append(colImg)
        var linkProduct = $("<a class='text-decoration-none text-dark'>")
        colImg.append(linkProduct)
        var imgProduct = $("<img class='w-100'>")
        colImg.append(imgProduct)
        var colText = $("<div class='col-7'>")
        bigRow.append(colText)
        var link = $("<a class='noDeco'>")
        link.attr("data-product-id", i)
        link.attr("href","product.html?produit_id=" + i)
        var titleProduct = $("<h4 class='titre styling'>")
        link.append(titleProduct)
        colText.append(link)
        var textProduct = $("<p>")
        colText.append(textProduct)
        var btnDiv = $("<div class='btn-group'>")
        colText.append(btnDiv)
        var btn = $("<button class='btn-secondary btn-sm' type='button'>")
        btnDiv.append(btn)
        btn.html("color")
        var btnDown = $("<button class='btn btn-sm btn-secondary dropdown-toggle dropdown-toggle-split'type='button'data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>")
        colText.append(btnDown)
        var bullShit = $("<span class='sr-only'>")
        btnDown.append(bullShit)
        bullShit.html("Toggle Dropdown")
        var menuDown = $(" <div class='dropdown-menu'>")
        colText.append(menuDown)
        var btnDiv2 = $("<div class='btn-group'>")
        colText.append(btnDiv2)
        var btn2 = $("<button class='btn-secondary btn-sm' type='button'>")
        btnDiv2.append(btn2)
        btn2.html("size")
        var btnDown2 = $("<button class='btn btn-sm btn-secondary dropdown-toggle dropdown-toggle-split'type='button'data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>")
        colText.append(btnDown2)
        var bullShit2 = $("<span class='sr-only'>")
        btnDown2.append(bullShit2)
        bullShit2.html("Toggle Dropdown")
        var menuDown2 = $(" <div class='dropdown-menu'>")
        colText.append(menuDown2)
        colPrice = $("<div class='col-2'>")
        bigRow.append(colPrice)
        var titlePrice = $("<h3>")
        colPrice.append(titlePrice)


        titleProduct.html(catalog[i].name)
        textProduct.html(catalog[i].description)
        imgProduct.attr("src", catalog[i].thumb)
        titlePrice.html(catalog[i].price + "$")
    }

})